# Generated by Django 5.2.5 on 2025-08-10 12:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('race', models.CharField(blank=True, max_length=50)),
                ('height', models.JSONField(blank=True, default=list)),
                ('weight', models.JSONField(blank=True, default=list)),
                ('eye_color', models.CharField(blank=True, max_length=30)),
                ('hair_color', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('alter_egos', models.CharField(blank=True, max_length=100)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('place_of_birth', models.CharField(blank=True, max_length=200)),
                ('first_appearance', models.CharField(blank=True, max_length=200)),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('alignment', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_affiliation', models.TextField(blank=True)),
                ('relatives', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PowerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intelligence', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('strength', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('speed', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('power', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('base', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('appearance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hero.appearance')),
                ('biography', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hero.biography')),
                ('connections', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hero.connections')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hero.image')),
                ('powerstats', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hero.powerstats')),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hero.work')),
            ],
        ),
    ]
