# Generated by Django 5.2.5 on 2025-08-10 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_powerstats_combat_alter_hero_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerstats',
            name='durability',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
